subpathauto.settings:
  type: config_object
  label: 'Subpathauto settings'
  mapping:
    depth:
      type: integer
      label: 'Maximum depth of sub-paths to alias'
    process_admin_routes:
      type: boolean
      label: 'Apply sub-paths aliasing on admin routes as well'
